### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by akdukaan** [akdukaan/DrSleep#2]
Unsure what causes it but here's the error that showed up in console

>.... [13:02:08 WARN]: [DrSleep] Task #541 for DrSleep v0.0.6 generated an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_242]
at org.acornmc.drsleep.DrSleep.lambda$onEnable$0(DrSleep.java:36) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Purpur-666]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Purpur-666]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1362) ~[patched_1.16.1.jar:git-Purpur-666]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.1.jar:git-Purpur-666]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1281) ~[patched_1.16.1.jar:git-Purpur-666]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1007) ~[patched_1.16.1.jar:git-Purpur-666]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.1.jar:git-Purpur-666]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

It looks like someone did not come off of the nosleep list because of this

**Comment by akdukaan** [comment]
Fixed in 0.0.7
